-- Phase 3: Fix Function Search Path Security Issues
-- Add SET search_path = public to all SECURITY DEFINER functions

-- Fix all functions that lack proper search_path setting
ALTER FUNCTION public.update_customer_rental_stats() SET search_path = public;
ALTER FUNCTION public.update_accounting_updated_at() SET search_path = public;
ALTER FUNCTION public.generate_receipt_number() SET search_path = public;
ALTER FUNCTION public.generate_voucher_number() SET search_path = public;
ALTER FUNCTION public.generate_discount_number() SET search_path = public;
ALTER FUNCTION public.normalize_plate_number(text) SET search_path = public;
ALTER FUNCTION public.update_vehicle_insurance_updated_at() SET search_path = public;
ALTER FUNCTION public.create_receipt_for_contract() SET search_path = public;
ALTER FUNCTION public.create_voucher_for_maintenance() SET search_path = public;
ALTER FUNCTION public.update_notification_updated_at() SET search_path = public;
ALTER FUNCTION public.create_smart_notification(text, text, varchar, varchar, varchar, varchar, uuid, jsonb, uuid, text[], boolean, timestamptz, text[]) SET search_path = public;
ALTER FUNCTION public.create_owner_commission_voucher() SET search_path = public;
ALTER FUNCTION public.handle_new_user() SET search_path = public;
ALTER FUNCTION public.cleanup_old_activity_logs() SET search_path = public;
ALTER FUNCTION public.validate_password_strength(text) SET search_path = public;
ALTER FUNCTION public.track_failed_login(inet, text, text) SET search_path = public;
ALTER FUNCTION public.is_ip_blocked(inet) SET search_path = public;
ALTER FUNCTION public.save_profitability_snapshot(varchar, uuid, jsonb, date, date) SET search_path = public;
ALTER FUNCTION public.get_owner_balance(uuid) SET search_path = public;
ALTER FUNCTION public.validate_voucher_payment(uuid, numeric) SET search_path = public;
ALTER FUNCTION public.check_balance_before_voucher() SET search_path = public;
ALTER FUNCTION public.get_profitability_comparison(varchar, uuid, date, date, date, date) SET search_path = public;
ALTER FUNCTION public.check_profitability_thresholds() SET search_path = public;
ALTER FUNCTION public.update_updated_at_profitability() SET search_path = public;
ALTER FUNCTION public.generate_maintenance_predictions(uuid) SET search_path = public;
ALTER FUNCTION public.update_maintenance_predictions_updated_at() SET search_path = public;
ALTER FUNCTION public.check_insurance_expiry() SET search_path = public;
ALTER FUNCTION public.ensure_cost_center_for_entity(varchar, uuid, text, text) SET search_path = public;
ALTER FUNCTION public.create_vehicle_cost_center() SET search_path = public;
ALTER FUNCTION public.create_customer_cost_center() SET search_path = public;
ALTER FUNCTION public.generate_financial_predictions(varchar, uuid, integer) SET search_path = public;
ALTER FUNCTION public.detect_financial_anomalies() SET search_path = public;
ALTER FUNCTION public.analyze_customer_behavior(uuid) SET search_path = public;
ALTER FUNCTION public.vehicle_maintenance_before_update_validate() SET search_path = public;
ALTER FUNCTION public.calculate_maintenance_total_cost(uuid) SET search_path = public;
ALTER FUNCTION public.update_maintenance_cost() SET search_path = public;
ALTER FUNCTION public.deduct_inventory_stock() SET search_path = public;
ALTER FUNCTION public.update_maintenance_timestamps() SET search_path = public;
ALTER FUNCTION public.write_activity(text, text, uuid, text, jsonb) SET search_path = public;
ALTER FUNCTION public.vehicle_maintenance_after_insert_activity() SET search_path = public;
ALTER FUNCTION public.vehicle_maintenance_after_update_activity() SET search_path = public;
ALTER FUNCTION public.maintenance_parts_used_activity() SET search_path = public;
ALTER FUNCTION public.check_and_notify_customer_arrears() SET search_path = public;
ALTER FUNCTION public.update_updated_at_column() SET search_path = public;